name: Merge main branch to development branch
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge-main-to-development:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge and push
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge main
          git push
