name: Validate development branch mergeability
on:
  pull_request:
    branches: [main]

jobs:
  validate-mergeability:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Local merge
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge origin/${GITHUB_HEAD_REF}
